export const fonts = {
  size: {
    xsmall: 12,
    small: 16,
    regular: 20,
    medium: 24,
    large: 32,
    xlarge: 36,
  },
  family: {
    black: 'Gilroy-Black',
    blackItalic: 'Gilroy-BlackItalic',
    bold: 'Gilroy-Bold',
    boldItalic: 'Gilroy-BoldItalic',
    extraBold: 'Gilroy-ExtraBold',
    extraBoldItalic: 'Gilroy-ExtraBoldItalic',
    heavy: 'Gilroy-Heavy',
    heavyItalic: 'Gilroy-HeavyItalic',
    light: 'Gilroy-Light',
    lightItalic: 'Gilroy-LightItalic',
    medium: 'Gilroy-Medium',
    mediumItalic: 'Gilroy-MediumItalic',
    regular: 'Gilroy-Regular',
    regularItalic: 'Gilroy-RegularItalic',
    semiBold: 'Gilroy-SemiBold',
    semiBoldItalic: 'Gilroy-SemiBoldItalic',
    thin: 'Gilroy-Thin',
    thinItalic: 'Gilroy-ThinItalic',
    ultraLight: 'Gilroy-UltraLight',
    ultraLightItalic: 'Gilroy-UltraLightItalic',
  },
};
